### PR TITLE
fix: ignore non-FEEL properties in the FEEL rule

### LINKED ISSUE #53: `feel` Rule Reports False Positives
The `feel` rule matches any property that starts with `=` regardless of whether this property can be a FEEL expression.

```xml
<bpmn:serviceTask name="==5" />
```

will lead to a report that `name` is not a valid feel expression.

A possible solution could be adding metadata to the [camunda-bpmn-moddle](https://github.com/camunda/camunda-bpmn-moddle/) extension.

Example:

```json
{
  "name": "InputOutputParameter",
  "properties": [
    {
      "name": "name",
      "isAttr": true,
      "type": "String"
    },
    {
      "name": "value",
      "isBody": true,
      "type": "String",
      "meta": {
        "feel": true
      }
    },
    {
      "name": "definition",
      "type": "InputOutputParameterDefinition"
    }
  ]
},
```

We'll have to investigate whether this works for all FEEL properties. Alternatively, we could have a list of properties that are supposed to be linted.

### PR DESCRIPTION
**Pull request by jarekdanielak**
Closes https://github.com/camunda/bpmnlint-plugin-camunda-compat/issues/53

### Proposed Changes

 

Ignore non-FEEL properties even if they are formatted like a FEEL expression.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: rules/camunda-cloud/feel.js [hunk 1]
```diff
@@ -17,6 +17,19 @@ const { ERROR_TYPES } = require('../utils/error-types');
 const { skipInNonExecutableProcess } = require('../utils/rule');
 const { annotateRule } = require('../helper');
 
+// Properties ignored globally
+const IGNORED_PROPERTIES = [
+  'name'
+];
+
+// Properties ignored only for specific element types
+const IGNORED_PROPERTIES_BY_TYPE = {
```
Comment (ev-codes) [inline rules/camunda-cloud/feel.js:26]: *suggestion:* consider also adding similar type properties:
```
  'zeebe:CalledDecision': [ 'resultVariable' ],
  'zeebe:Script': [ 'resultVariable' ]
```

They seem similar to `zeebe:Input/Output.target` in that they would often contain a process variable name.

**Review by ev-codes — APPROVED** [review]
LGTM, thanks!

I left a few optional suggestions of additional type-dependent properties to ignore

File: rules/camunda-cloud/feel.js (hunk 1 above)
Comment (jarekdanielak) [reply rules/camunda-cloud/feel.js:26]: Thanks! Added these two.

**Review by philippfromme — APPROVED** [review]
Looks good. Let's not forget to look into a real solution soon. 🤞🏻

**Comment by barmac** [comment]
> Looks good. Let's not forget to look into a real solution soon. 🤞🏻

Absolutely as the current fix is not bulletproof: https://github.com/camunda/linting/pull/153#issuecomment-4304132687
